### ISSUE TITLE
运行VCamNetSample失败

### ISSUE THREAD

**Issue by gitqin** [smourier/VCamNetSample#3]
使用VCamNetSampleSource 编译出来VCamNetSampleSource.dll 
regsvr32 VCamNetSampleSource.dll 报错
模块“VCamNetSampleSource.d“已加载，但找不到入口点DllRegisterServer.
请确保"VCamNetSampleSource.d"为有效的 DLL 或 OCX 文件，然后重试。

注册预留的VCamNetSampleSource.comhost.dll 无法注册到HKLM中  只在HKCR 运行VCamNetSample 还是会报错未注册

**Comment by smourier** [comment]
I don't speek that language, please translate your message to english or I will close this issue
